# Generated by Django 4.1.7 on 2023-03-23 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_Card',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('c1c66751-63fb-4bba-8b1d-b2d6e4c69cf1'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('url', models.TextField()),
                ('text', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
