# Generated by Django 4.1.7 on 2023-03-23 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0003_alter_order_card_id_alter_order_card_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_card',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e0bcb1ba-950a-4de6-ad3b-913347d31efc'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
