# Generated by Django 4.1.7 on 2023-03-23 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0006_alter_order_card_id_alter_order_card_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c1d04af-cccf-4274-8c47-9684ce9e2a81'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_card',
            name='status',
            field=models.ForeignKey(default='m', on_delete=django.db.models.deletion.CASCADE, to='site_mainPage.order_status'),
        ),
    ]
