# Generated by Django 4.1.7 on 2023-03-23 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0007_order_status_alter_order_card_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0748d7f-c780-46ab-926e-eadeef6694d9'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_card',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Book availability', max_length=1),
        ),
        migrations.DeleteModel(
            name='order_Status',
        ),
    ]
