# Generated by Django 4.1.7 on 2023-03-23 08:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0008_alter_order_card_id_alter_order_card_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_card',
            name='text',
        ),
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('027a20b8-2421-4647-b02f-27f0fb39f104'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
