# Generated by Django 4.1.7 on 2023-03-23 08:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0009_remove_order_card_text_alter_order_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('691d4709-70f2-45df-8185-32e10565658f'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
