# Generated by Django 4.1.7 on 2023-03-23 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('site_mainPage', '0010_alter_order_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_card',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e48ffd1c-3d1f-4191-be53-603becf4ead8'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
